name = "DocumenterModuleProblem"
uuid = "fd3792b1-f2cc-4fae-8090-2c800d496f5d"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.0"

[deps]
BrokenDoctest = "ac000179-e1b3-44d7-a7a6-3bb2cde350b2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
